import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Locale = 'ar' | 'en'

type Messages = typeof ar

const ar = {
  nav: { home: 'الرئيسية', features: 'المميزات', how: 'كيف يعمل', lawyers: 'حلول المحامين', security: 'الأمان', faq: 'الأسئلة الشائعة', login: 'تسجيل الدخول', language: 'English', start: 'ابدأ الآن', menuOpen: 'فتح القائمة', menuClose: 'إغلاق القائمة', aria: 'التنقل الرئيسي' },
  brand: { name: 'سَنَد', homeAria: 'سَنَد - الصفحة الرئيسية', logoAlt: 'شعار سَنَد' },
  hero: { eyebrow: 'ذكاء قانوني مصمم للعمل الاحترافي', title: 'حوّل مستنداتك القانونية إلى', titleAccent: 'قرارات أكثر ذكاءً.', description: 'من تحليل العقود واكتشاف المخاطر إلى المساعدة القانونية الذكية، اجعل الذكاء الاصطناعي جزءاً موثوقاً من فريقك القانوني.', designed: 'مصمم للمحامين والمهنيين القانونيين', workspaceAria: 'مساحة عمل لتحليل مستند قانوني بالذكاء الاصطناعي', workspaceAlt: 'مساحة عمل قانونية تعرض عقداً وتحليل المخاطر والمساعد القانوني', analysis: 'تحليل المستند', analyzing: 'جاري تحليل المستند', risk: 'مستوى المخاطر', riskMedium: 'متوسط', ai: 'AI Legal Assistant', important: '٤ بنود مهمة' },
  trust: { intro: 'مصمم لبيئات العمل القانونية الحديثة', items: ['خصوصية عالية', 'تشفير البيانات', 'صلاحيات مرنة', 'بنية مؤسسية'] },
  productVisual: { aria: 'نموذج توضيحي لواجهة تحليل عقد قانوني', crumb: 'المستندات / عقود', title: 'اتفاقية خدمات استشارية', share: 'مشاركة المستند', draft: 'مسودة · ١٢ صفحة', documentTitle: 'اتفاقية تقديم خدمات', body1: 'تم إبرام هذه الاتفاقية في تاريخ', body2: 'بين الطرف الأول والطرف الثاني، وفقاً للشروط والأحكام الموضحة أدناه.', clause: '٤. بند المسؤولية', highlight: 'لا تتجاوز مسؤولية أي طرف عن الأضرار غير المباشرة أو التبعية قيمة المقابل المالي المدفوع خلال الاثني عشر شهراً السابقة.', body3: 'ويتحمل كل طرف مسؤولية التزاماته النظامية والتعاقدية المنصوص عليها في هذه الاتفاقية.', insights: 'رؤى المستند', risk: 'مستوى المخاطر', selected: 'البند المحدد', liability: 'بند المسؤولية', insight: 'يتضمن سقفاً للمسؤولية. يُنصح بالتحقق من توافقه مع نطاق العمل.', suggestion: 'عرض الاقتراح', complete: 'اكتمل التحليل' },
  reference: { aria: 'مساحة عمل لتحليل مستند قانوني بالذكاء الاصطناعي', alt: 'مساحة عمل قانونية تعرض عقداً وتحليل المخاطر والمساعد القانوني', status: 'جاري تحليل المستند', cta: 'استكشف المنصة', laptopEyebrow: 'رؤية أوضح للمستند', laptopTitle: 'راجع البنود المهمة', laptopTitle2: 'في مساحة واحدة.', laptopText: 'تظهر الملاحظات، البنود التي تحتاج إلى مراجعة، ومستوى المخاطر بجوار المستند مباشرة.', laptopCta: 'استكشف تجربة التحليل', laptopAlt: 'حاسوب محمول يعرض المساعد القانوني وتحليل عقد خدمات' },
  workflow: { eyebrow: 'من المستند إلى القرار', title: 'تدفق عمل يتحرك', titleAccent: 'مع طريقة تفكيرك.', text: 'من أول صفحة إلى آخر قرار، تبقى كل إشارة في سياقها وتحت مراجعتك المهنية.', paper: 'عقد اتفاقية خدمات', paperStatus: 'جاري التحليل', stages: [['ارفع مستندك', 'ابدأ من عقد أو ملف قانوني، مع الحفاظ على بنية المستند وسياقه.'], ['يحلل الذكاء الاصطناعي المستند', 'يستخرج البنود الجوهرية ويجمع الإشارات التي تستحق انتباهك.'], ['اكتشف البنود التي تستحق المراجعة', 'تظهر المخاطر بصرياً مع مستوى واضح وإشارة إلى النص الأصلي.'], ['اتخذ قراراً أكثر وضوحاً', 'اسأل المساعد القانوني واحصل على إجابات مرتبطة بمستنداتك.']] },
  problems: { eyebrow: 'تحديات مألوفة', title: 'العمل القانوني لا يحتاج إلى', title2: 'مزيد من التعقيد.', text: 'الوقت الذي يضيع في المهام المتكررة هو وقت كان يمكن أن يذهب للحكم القانوني والاستراتيجية.', items: ['قراءة مئات الصفحات', 'البحث الطويل عن المعلومات', 'مراجعة العقود يدوياً', 'تكرار الأعمال الروتينية', 'صعوبة تنظيم المستندات', 'وقت أقل للعمل عالي القيمة'] },
  features: { eyebrow: 'منصة واحدة، تدفق عمل أوضح', title: 'كل ما تحتاجه للعمل', title2: 'القانوني الذكي.', explore: 'استكشف الميزة', items: [['تحليل المستندات', 'ارفع المستندات ودع الذكاء الاصطناعي يستخرج البنود والمعلومات المهمة.'], ['المساعد القانوني الذكي', 'اسأل بلغة طبيعية واحصل على إجابات مرتبطة بمراجع المستند.'], ['صياغة المستندات', 'أنشئ مسودات قانونية واضحة مع الحفاظ على السياق الأساسي.'], ['اكتشاف المخاطر', 'حدّد البنود التي تستحق المراجعة قبل أن تصبح مصدر قلق.'], ['البحث الذكي', 'اعثر على المعلومة الصحيحة دون التنقل بين عشرات الصفحات.'], ['إدارة المعرفة', 'نظّم مستنداتك لتصبح المعرفة في متناول فريقك وقت الحاجة.']] },
  product: { eyebrow: 'تجربة المنتج', title: 'شاهد الذكاء القانوني', title2: 'أثناء العمل.', text: 'تتحول المستندات إلى مساحة عمل تضع البنود المهمة، مستوى المخاطر، والإجراء المقترح في متناولك.', stats: ['بنود للمراجعة', 'مستوى المخاطر'], status: 'اكتمل التحليل', clause: 'بند المسؤولية', needsReview: 'يحتاج إلى مراجعة', aria: 'عرض توضيحي لمساحة العمل القانونية' },
  analysis: { eyebrow: 'تحليل المستندات', title: 'افهم ما بين السطور قبل اتخاذ القرار.', text: 'تقرأ سَنَد المستند معك، وتساعدك على الوصول إلى البنود الجوهرية والمخاطر المحتملة في سياقها.', bullets: ['ملخصات منظمة لكل مستند', 'تحديد البنود والمخاطر للمراجعة', 'اقتراحات مرتبطة بالنص الأصلي'], cta: 'شاهد كيف يعمل', review: 'مراجعة العقد', analyzed: 'تم التحليل', clauseNo: 'البند ٤.٢', clause: 'يلتزم مقدم الخدمة بتعويض الطرف الآخر عن الأضرار المباشرة الناتجة عن الإخلال الجوهري.', risk: 'مستوى المخاطر: متوسط', ceiling: 'سقف المسؤولية يحتاج إلى مراجعة', recommendation: 'عرض التوصية', noteTitle: 'ملاحظة الذكاء الاصطناعي', note: 'تحقق من توافق الاستثناءات مع التزاماتك التجارية.' },
  assistant: { eyebrow: 'المساعد القانوني', title: 'إجابات تستند إلى', title2: 'مستنداتك.', text: 'تحاور مع مساعد يفهم سياق ملفك ويعيدك دائماً إلى المرجع المناسب، لتبقى أنت صاحب القرار.', callout: 'اسأل، راجع، ثم اتخذ قرارك بثقة.', header: 'المساعد القانوني', more: 'المزيد', question: 'ما أهم البنود التي تحتاج إلى مراجعة في هذا العقد؟', answer: 'وجدت ٤ بنود تستحق المراجعة. أهمها بند المسؤولية وحدود التعويض.', source: 'اتفاقية الخدمات · البند ٤.٢', summary: 'ملخص التحليل', updated: 'محدث الآن', rows: [['بند المسؤولية', 'مراجعة مهمة'], ['حدود التعويض', 'متوسط'], ['مدة الاتفاقية', 'واضح']], suggestions: ['اشرح بند المسؤولية', 'اقترح تعديلاً'], input: 'اكتب سؤالك عن المستند…', demo: 'شاهد الديمو', demoEyebrow: 'عرض توضيحي', demoTitle: 'شاهد المساعد القانوني أثناء العمل', demoClose: 'إغلاق العرض التوضيحي' },
  security: { eyebrow: 'الأمن والخصوصية', title: 'بياناتك القانونية تستحق', title2: 'أعلى درجات العناية.', text: 'صُممت المنصة مع وضع أمن البيانات والخصوصية في الاعتبار، حتى تتمكن من العمل بثقة ووضوح.', cta: 'تعرف على نهجنا في الأمان', alt: 'رمز أمان قانوني', items: [['تشفير البيانات', 'حماية للمعلومات أثناء النقل والمعالجة'], ['وصول مضبوط', 'أدوار وصلاحيات تتوافق مع فريقك'], ['سجل قابل للمراجعة', 'وضوح أكبر في أنشطة مساحة العمل'], ['خصوصية المستندات', 'بيئة عمل تحترم حساسية ملفاتك']] },
  steps: { eyebrow: 'بساطة في كل خطوة', title: 'من المستند إلى الرؤية', title2: 'في تدفق عمل واضح.', items: ['ارفع مستنداتك', 'دع الذكاء الاصطناعي يحللها', 'راجع النتائج والرؤى', 'اتخذ القرار بثقة'] },
  faq: { eyebrow: 'الأسئلة الشائعة', title: 'أسئلة واضحة.', title2: 'إجابات مباشرة.', text: 'إذا لم تجد ما تبحث عنه، يسعدنا أن نساعدك.', contact: 'تواصل معنا', items: [['ما هي منصة سَنَد؟', 'منصة عمل قانوني ذكية تساعد الفرق على تحليل المستندات والبحث فيها وصياغة مسودات أولية بشكل أكثر تنظيماً.'], ['هل يمكنني رفع مستنداتي القانونية؟', 'صُممت واجهات المنصة لتدعم العمل بالمستندات القانونية مع ضوابط وصول واضحة ضمن بيئة العمل.'], ['كيف يتم تحليل المستندات؟', 'تستخرج المنصة البنود والنقاط المهمة وتعرضها في سياقها لتراجعها وتتخذ قرارك المهني.'], ['هل بياناتي آمنة؟', 'نضع أمن البيانات والخصوصية في صميم التصميم، مع خيارات لإدارة الوصول وسجل قابل للمراجعة.'], ['هل يدعم فريقاً كاملاً؟', 'نعم، صُممت التجربة لتناسب العمل الفردي والفرق القانونية، مع أدوار وصلاحيات قابلة للتوسّع.'], ['هل يحل الذكاء الاصطناعي محل المحامي؟', 'لا. المخرجات تساعد في تسريع العمل وتحتاج دائماً إلى مراجعة وحكم مهني من مختص قانوني مؤهل.']] },
  plans: { eyebrow: 'خطط اشتراك مرنة', title: 'اختر مساحة العمل', title2: 'المناسبة لك.', text: 'سواء كنت محاميًا أو تستخدم المنصة لإدارة مستنداتك الشخصية، كل خطة تمنحك أدوات قانونية ذكية باشتراك واضح.', badge: 'الأكثر اختيارًا للمحامين', monthly: 'جنيه / شهريًا', subscribe: 'ابدأ الاشتراك', close: 'إغلاق خطط الاشتراك', plans: [['شخصي', 'للأفراد والباحثين عن مساعدة قانونية ذكية', '١٤٩', ['تحليل المستندات', 'المساعد القانوني الذكي', 'ملخصات ومخاطر واضحة']], ['مهني', 'للمحامين والممارسين القانونيين', '٢٩٩', ['كل مزايا الشخصي', 'مراجعة العقود المتقدمة', 'سجل ومراجع لكل قرار']], ['فريق', 'للمكاتب والفرق القانونية', '٥٩٩', ['مساحات عمل متعددة', 'صلاحيات للفريق', 'دعم وأمان مؤسسي']]] },
  cta: { title: 'ابدأ مستقبل العمل', title2: 'القانوني اليوم.', text: 'قلل الأعمال المتكررة، وافهم مستنداتك بشكل أسرع، وامنح فريقك مساحة أكبر للعمل عالي القيمة.', disclaimer: 'لا تتخذ المنصة قرارات قانونية نيابةً عنك.' },
  footer: { tagline: 'ذكاء قانوني مصمم للمهنيين.', links: ['المميزات', 'الأمان', 'الأسئلة الشائعة'], copyright: '© ٢٠٢٦ سَنَد. جميع الحقوق محفوظة.' },
  a11y: { skip: 'انتقل إلى المحتوى', share: 'مشاركة المستند' },
  seo: { title: 'سَنَد | منصة الذكاء الاصطناعي القانونية', description: 'منصة ذكية تساعد المحامين والمهنيين القانونيين على تحليل المستندات وصياغة المحتوى القانوني والوصول إلى المعلومات بكفاءة أكبر.', ogDescription: 'ذكاء قانوني مصمم للعمل الاحترافي.' }
} as const

const en: any = {
  ...ar,
  nav: { home: 'Home', features: 'Features', how: 'How it works', lawyers: 'For lawyers', security: 'Security', faq: 'FAQ', login: 'Sign in', language: 'العربية', start: 'Get started', menuOpen: 'Open menu', menuClose: 'Close menu', aria: 'Main navigation' },
  brand: { name: 'Sanad', homeAria: 'Sanad - Home', logoAlt: 'Sanad logo' },
  hero: { eyebrow: 'Legal intelligence designed for professional work', title: 'Turn your legal documents into', titleAccent: 'smarter decisions.', description: 'From contract analysis and risk detection to intelligent legal assistance, make AI a trusted part of your legal team.', designed: 'Designed for lawyers and legal professionals', workspaceAria: 'AI-powered legal document analysis workspace', workspaceAlt: 'Legal workspace showing a contract, risk analysis and legal assistant', analysis: 'Document analysis', analyzing: 'Analyzing document', risk: 'Risk level', riskMedium: 'Medium', ai: 'AI Legal Assistant', important: '4 key clauses' },
  trust: { intro: 'Designed for modern legal workspaces', items: ['High privacy', 'Data encryption', 'Flexible permissions', 'Enterprise-ready'] },
  productVisual: { aria: 'Legal contract analysis interface preview', crumb: 'Documents / Contracts', title: 'Consulting services agreement', share: 'Share document', draft: 'Draft · 12 pages', documentTitle: 'Services agreement', body1: 'This agreement was entered into on', body2: 'between the first and second parties, under the terms and conditions below.', clause: '4. Liability clause', highlight: 'Neither party’s liability for indirect or consequential damages may exceed the consideration paid during the previous twelve months.', body3: 'Each party remains responsible for its legal and contractual obligations under this agreement.', insights: 'Document insights', risk: 'Risk level', selected: 'Selected clause', liability: 'Liability clause', insight: 'Includes a liability cap. Check that it aligns with the scope of work.', suggestion: 'View suggestion', complete: 'Analysis complete' },
  reference: { aria: 'AI-powered legal document analysis workspace', alt: 'Legal workspace showing a contract, risk analysis and legal assistant', status: 'Analyzing document', cta: 'Explore the platform', laptopEyebrow: 'A clearer view of every document', laptopTitle: 'Review key clauses', laptopTitle2: 'in one workspace.', laptopText: 'See notes, clauses that need review, and risk levels beside the document.', laptopCta: 'Explore analysis', laptopAlt: 'Laptop showing a legal assistant and services contract analysis' },
  workflow: { eyebrow: 'From document to decision', title: 'A workflow that moves', titleAccent: 'with the way you think.', text: 'From the first page to the final decision, every signal stays in context and under your professional review.', paper: 'Services agreement', paperStatus: 'Analyzing', stages: [['Upload your document', 'Start with a contract or legal file while preserving its structure and context.'], ['AI analyzes the document', 'Extract key clauses and gather the signals that deserve your attention.'], ['Find clauses worth reviewing', 'See risks visually with a clear level and a link to the original text.'], ['Make a clearer decision', 'Ask the legal assistant and get answers grounded in your documents.']] },
  problems: { eyebrow: 'Familiar challenges', title: 'Legal work does not need', title2: 'more complexity.', text: 'Time lost to repetitive tasks is time that could go to legal judgment and strategy.', items: ['Reading hundreds of pages', 'Long searches for information', 'Manual contract review', 'Repeating routine work', 'Disorganized documents', 'Less time for high-value work'] },
  features: { eyebrow: 'One platform, a clearer workflow', title: 'Everything you need for', title2: 'smarter legal work.', explore: 'Explore feature', items: [['Document analysis', 'Upload documents and let AI extract key clauses and information.'], ['Intelligent legal assistant', 'Ask in natural language and get answers linked to document sources.'], ['Document drafting', 'Create clear legal drafts while preserving the original context.'], ['Risk detection', 'Identify clauses worth reviewing before they become a concern.'], ['Smart search', 'Find the right information without navigating dozens of pages.'], ['Knowledge management', 'Organize documents so knowledge stays within reach of your team.']] },
  product: { eyebrow: 'Product experience', title: 'Watch legal intelligence', title2: 'at work.', text: 'Documents become a workspace that puts key clauses, risk levels and suggested actions within reach.', stats: ['clauses to review', 'risk level'], status: 'Analysis complete', clause: 'Liability clause', needsReview: 'Needs review', aria: 'Legal workspace product demo' },
  analysis: { eyebrow: 'Document analysis', title: 'Understand between the lines before you decide.', text: 'Sanad reads the document with you and helps surface key clauses and potential risks in context.', bullets: ['Organized summaries for every document', 'Flag clauses and risks for review', 'Suggestions linked to the original text'], cta: 'See how it works', review: 'Contract review', analyzed: 'Analyzed', clauseNo: 'Clause 4.2', clause: 'The service provider shall indemnify the other party for direct damages resulting from a material breach.', risk: 'Risk level: Medium', ceiling: 'Liability cap needs review', recommendation: 'View recommendation', noteTitle: 'AI note', note: 'Check that the exceptions align with your commercial obligations.' },
  assistant: { eyebrow: 'Legal assistant', title: 'Answers grounded in', title2: 'your documents.', text: 'Chat with an assistant that understands your file context and always points you back to the right source, so you stay in control.', callout: 'Ask, review, then decide with confidence.', header: 'Legal assistant', more: 'More', question: 'Which clauses in this contract need review?', answer: 'I found 4 clauses worth reviewing. The key ones concern liability and indemnity limits.', source: 'Services agreement · Clause 4.2', summary: 'Analysis summary', updated: 'Updated now', rows: [['Liability clause', 'Priority review'], ['Indemnity limits', 'Medium'], ['Agreement term', 'Clear']], suggestions: ['Explain liability', 'Suggest an edit'], input: 'Ask about the document…', demo: 'Watch demo', demoEyebrow: 'Product demo', demoTitle: 'Watch the legal assistant at work', demoClose: 'Close product demo' },
  security: { eyebrow: 'Security & privacy', title: 'Your legal data deserves', title2: 'the highest care.', text: 'The platform is designed with data security and privacy in mind, so you can work with confidence and clarity.', cta: 'Explore our security approach', alt: 'Legal security symbol', items: [['Data encryption', 'Protecting information in transit and at rest'], ['Controlled access', 'Roles and permissions that fit your team'], ['Audit-ready history', 'Clearer visibility into workspace activity'], ['Document privacy', 'A workspace that respects sensitive files']] },
  steps: { eyebrow: 'Simple at every step', title: 'From document to insight', title2: 'in a clear workflow.', items: ['Upload your documents', 'Let AI analyze them', 'Review findings and insights', 'Decide with confidence'] },
  faq: { eyebrow: 'Frequently asked questions', title: 'Clear questions.', title2: 'Direct answers.', text: 'If you cannot find what you need, we are happy to help.', contact: 'Contact us', items: [['What is Sanad?', 'A smart legal workspace that helps teams analyze documents, search them and draft initial content in a more organized way.'], ['Can I upload my legal documents?', 'The platform supports legal document workflows with clear access controls within your workspace.'], ['How are documents analyzed?', 'The platform extracts important clauses and points and presents them in context for your professional review.'], ['Is my data secure?', 'Data security and privacy are at the heart of the design, with access management and audit-ready history.'], ['Does it support a full team?', 'Yes. The experience supports individuals and legal teams with scalable roles and permissions.'], ['Does AI replace a lawyer?', 'No. Outputs accelerate the work but always require review and professional judgment from a qualified legal specialist.']] },
  plans: { eyebrow: 'Flexible subscription plans', title: 'Choose the workspace', title2: 'that fits you.', text: 'Whether you are a lawyer or managing personal documents, every plan gives you smart legal tools through a clear subscription.', badge: 'Most popular with lawyers', monthly: 'EGP / month', subscribe: 'Start subscription', close: 'Close subscription plans', plans: [['Personal', 'For individuals and anyone seeking smart legal support', '١٤٩', ['Document analysis', 'Intelligent legal assistant', 'Clear summaries and risks']], ['Professional', 'For lawyers and legal practitioners', '٢٩٩', ['Everything in Personal', 'Advanced contract review', 'Audit trail for every decision']], ['Team', 'For firms and legal teams', '٥٩٩', ['Multiple workspaces', 'Team permissions', 'Enterprise support and security']]] },
  cta: { title: 'Start the future of', title2: 'legal work today.', text: 'Reduce repetitive work, understand documents faster, and give your team more room for high-value work.', disclaimer: 'The platform does not make legal decisions on your behalf.' },
  footer: { tagline: 'Legal intelligence designed for professionals.', links: ['Features', 'Security', 'FAQ'], copyright: '© 2026 Sanad. All rights reserved.' },
  a11y: { skip: 'Skip to content', share: 'Share document' },
  seo: { title: 'Sanad | Legal AI platform', description: 'A smart platform that helps lawyers and legal professionals analyze documents, draft legal content and access information more efficiently.', ogDescription: 'Legal intelligence designed for professional work.' }
}

export const messages: Record<Locale, Messages> = { ar, en }

type I18nContextValue = { locale: Locale; lang: Messages; setLocale: (locale: Locale) => void }
const I18nContext = createContext<I18nContextValue | null>(null)

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => { const saved = localStorage.getItem('sanad-locale'); return saved === 'en' || saved === 'ar' ? saved : 'ar' })
  const setLocale = (next: Locale) => { setLocaleState(next); localStorage.setItem('sanad-locale', next) }
  const lang = messages[locale]
  useEffect(() => { document.documentElement.lang = locale; document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr'; document.title = lang.seo.title; const description = document.querySelector('meta[name="description"]'); if (description) description.setAttribute('content', lang.seo.description); const ogTitle = document.querySelector('meta[property="og:title"]'); if (ogTitle) ogTitle.setAttribute('content', lang.seo.title); const ogDescription = document.querySelector('meta[property="og:description"]'); if (ogDescription) ogDescription.setAttribute('content', lang.seo.ogDescription) }, [locale, lang])
  const value = useMemo(() => ({ locale, lang, setLocale }), [locale, lang])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n() { const value = useContext(I18nContext); if (!value) throw new Error('useI18n must be used inside I18nProvider'); return value }
